version: "3"
services:
  mariadb:
    image: linuxserver/mariadb:latest
    container_name: codilia_mariadb
    restart: always
    volumes:
      - path to mariadb data:/config
    environment:
      - MYSQL_ROOT_PASSWORD=secret password
      - MYSQL_DATABASE=codilia
      - MYSQL_USER=codilia
      - MYSQL_PASSWORD=secret password
      - PGID=1000
      - PUID=1000
      - TZ=Europe/London
  codilia:
    build: .
    container_name: codilia
    restart: always
    depends_on:
      - mariadb
    volumes:
      - path to config:/config
    environment:
      - DB_HOST=mariadb
      - DB_USER=codilia
      - DB_PASS=secret password
      - DB_NAME=codilia
      - DB_PORT=3306
      - PGID=1000
      - PUID=1000
      - TZ=Europe/London
    ports:
      - "3000:3000"
