version: "3"
services:
  mariadb:
    image: linuxserver/mariadb:latest
    container_name: codimd_mariadb
    restart: always
    volumes:
      - path to mariadb data:/config
    environment:
      - MYSQL_ROOT_PASSWORD=secret password
      - MYSQL_DATABASE=codimd
      - MYSQL_USER=codimd
      - MYSQL_PASSWORD=secret password
      - PGID=1000
      - PUID=1000
      - TZ=Europe/London
  codimd:
    build: .
    container_name: codimd
    restart: always
    depends_on:
      - mariadb
    volumes:
      - path to config:/config
    environment:
      - DB_HOST=mariadb
      - DB_USER=codimd
      - DB_PASS=secret password
      - DB_NAME=codimd
      - DB_PORT=3306
      - PGID=1000
      - PUID=1000
      - TZ=Europe/London
    ports:
      - "3000:3000"
